# Generated by Django 5.1 on 2024-08-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Введіть ім'я автора", max_length=50, verbose_name="Ім'я автора")),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть тег', max_length=20, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введіть назву статті', max_length=100, verbose_name='Назва статті')),
                ('date_of_publication', models.DateField(blank=True, help_text='Введіть дату публікації', null=True, verbose_name='Дата публікації')),
                ('author', models.ForeignKey(help_text='Оберіть автора статті', on_delete=django.db.models.deletion.CASCADE, to='newportal.author', verbose_name='Автор')),
                ('tags', models.ManyToManyField(help_text='Оберіть теги для статті', to='newportal.tag', verbose_name='Теги')),
            ],
        ),
    ]
