# Generated by Django 5.1 on 2024-08-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_text',
            field=models.TextField(default='Поле статті', help_text='Введіть текст статті', max_length=300, verbose_name='Текст статті'),
        ),
    ]
