# Generated by Django 5.1 on 2024-08-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0003_comment_savedarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Введіть текст коментаря'),
        ),
    ]
