# Generated by Django 5.1 on 2024-08-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0004_alter_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ім`я користувача')),
                ('email', models.EmailField(max_length=100, verbose_name='Пошта')),
                ('password', models.CharField(max_length=24, verbose_name='Пароль')),
            ],
        ),
    ]
