# Generated by Django 5.1 on 2024-08-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0005_adduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddUser',
        ),
    ]
