# Generated by Django 5.1 on 2024-09-04 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0009_alter_comment_text_alter_savedarticle_saved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Введіть текст коментаря'),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата збереження'),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
