# Generated by Django 5.1 on 2024-09-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0010_alter_comment_text_alter_savedarticle_saved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#ffffff', help_text='Background color in hex format', max_length=7)),
                ('font_color', models.CharField(default='#000000', help_text='Font color in hex format', max_length=7)),
                ('font_size', models.CharField(default='16px', help_text='Font size', max_length=10)),
            ],
        ),
    ]
