# Generated by Django 5.1 on 2024-09-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0011_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font_size',
            field=models.CharField(default='16px', max_length=10),
        ),
    ]
