# Generated by Django 5.1 on 2024-09-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0012_alter_sitesettings_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Кількість переглядів'),
        ),
    ]
