# Generated by Django 5.1 on 2024-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0014_alter_article_article_text_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_color',
            field=models.CharField(default='#002f31', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font_size',
            field=models.IntegerField(default=14),
        ),
    ]
