# Generated by Django 5.1 on 2024-09-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0016_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(default='Поле статті', max_length=1000, verbose_name='Текст статті'),
        ),
    ]
