# Generated by Django 5.1 on 2024-11-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0017_alter_article_article_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedFacade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_facade', models.CharField(choices=[('activity', 'activity'), ('count', 'count'), ('error', 'error'), ('word', 'word'), ('tracker', 'tracker')], default='error', max_length=20, verbose_name='Виберіть варіант дослідження')),
            ],
        ),
    ]
