# Generated by Django 5.1 on 2024-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0018_selectedfacade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedfacade',
            name='selected_facade',
            field=models.CharField(choices=[('word', 'word'), ('tracker', 'tracker'), ('error', 'error'), ('count', 'count'), ('activity', 'activity')], default='error', max_length=20, verbose_name='Виберіть варіант дослідження'),
        ),
    ]
