# Generated by Django 5.1 on 2025-01-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0019_alter_selectedfacade_selected_facade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProhibitedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'статтю', 'verbose_name_plural': 'Статті'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'автори', 'verbose_name_plural': 'Автори'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'коментар', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AlterModelOptions(
            name='savedarticle',
            options={'verbose_name': 'збережену статтю', 'verbose_name_plural': 'Збережені статті'},
        ),
        migrations.AlterModelOptions(
            name='selectedfacade',
            options={'verbose_name': 'звіт', 'verbose_name_plural': 'Звіти'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Налаштування сайту', 'verbose_name_plural': 'Налаштування сайту'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='userban',
            options={'verbose_name': 'Блокування користувача', 'verbose_name_plural': 'Блокування користувачів'},
        ),
        migrations.AlterField(
            model_name='selectedfacade',
            name='selected_facade',
            field=models.CharField(choices=[('error', 'error'), ('count', 'count'), ('word', 'word'), ('activity', 'activity'), ('tracker', 'tracker')], default='error', max_length=20, verbose_name='Виберіть варіант дослідження'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Введіть тег', max_length=20, verbose_name='Теги'),
        ),
    ]
