# Generated by Django 5.1 on 2025-02-17 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0020_prohibitedword_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedfacade',
            name='selected_facade',
            field=models.CharField(choices=[('count', 'count'), ('word', 'word'), ('tracker', 'tracker'), ('error', 'error'), ('activity', 'activity')], default='error', max_length=20, verbose_name='Виберіть варіант дослідження'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(36)]),
        ),
    ]
