# Generated by Django 5.1 on 2025-02-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0021_alter_selectedfacade_selected_facade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedfacade',
            name='selected_facade',
            field=models.CharField(choices=[('word', 'word'), ('error', 'error'), ('tracker', 'tracker'), ('activity', 'activity'), ('count', 'count')], default='error', max_length=20, verbose_name='Виберіть варіант дослідження'),
        ),
    ]
