# Generated by Django 5.1 on 2025-02-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0022_alter_selectedfacade_selected_facade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedfacade',
            name='selected_facade',
            field=models.CharField(choices=[('error', 'error'), ('activity', 'activity'), ('tracker', 'tracker'), ('count', 'count'), ('word', 'word')], default='error', max_length=20, verbose_name='Виберіть варіант дослідження'),
        ),
    ]
