# Generated by Django 5.1 on 2025-02-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0025_alter_selectedfacade_selected_facade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedfacade',
            name='selected_facade',
            field=models.CharField(choices=[('tracker', 'tracker'), ('word', 'word'), ('count', 'count'), ('error', 'error'), ('activity', 'activity')], default='error', max_length=20, verbose_name='Виберіть варіант дослідження'),
        ),
    ]
