# Generated by Django 5.1 on 2025-08-06 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0028_delete_sitesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_color', models.CharField(default='#000000', max_length=7)),
                ('background_color', models.CharField(default='#002f31', max_length=7)),
                ('font_size', models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(36)])),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.AlterField(
            model_name='selectedfacade',
            name='selected_facade',
            field=models.CharField(choices=[('word', 'word'), ('tracker', 'tracker'), ('activity', 'activity'), ('count', 'count'), ('error', 'error')], default='error', max_length=20, verbose_name='Виберіть варіант дослідження'),
        ),
    ]
