# Generated by Django 5.1 on 2025-08-06 13:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0029_sitesettings_alter_selectedfacade_selected_facade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedfacade',
            name='selected_facade',
            field=models.CharField(choices=[('error', 'error'), ('count', 'count'), ('tracker', 'tracker'), ('word', 'word'), ('activity', 'activity')], default='error', max_length=20, verbose_name='Виберіть варіант дослідження'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.CreateModel(
            name='UserSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_color', models.CharField(default='#ffffff', max_length=7)),
                ('background_color', models.CharField(default='#002f31', max_length=7)),
                ('font_size', models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(36)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
