# Generated by Django 5.1 on 2025-08-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newportal', '0030_alter_selectedfacade_selected_facade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.AlterField(
            model_name='selectedfacade',
            name='selected_facade',
            field=models.CharField(choices=[('tracker', 'tracker'), ('error', 'error'), ('count', 'count'), ('activity', 'activity'), ('word', 'word')], default='error', max_length=20, verbose_name='Виберіть варіант дослідження'),
        ),
    ]
